"""Adjust fk relationship

Revision ID: 265ccf836992
Revises: 7fd8d0d4468c
Create Date: 2025-05-28 05:28:39.358075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265ccf836992'
down_revision = '7fd8d0d4468c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
