"""Added account api data

Revision ID: e56e5cd2be1d
Revises: 
Create Date: 2022-10-23 21:37:04.711122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56e5cd2be1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character', sa.String(length=100), nullable=True),
    sa.Column('power_level', sa.String(length=100), nullable=True),
    sa.Column('saga_or_movie', sa.String(length=100), nullable=True),
    sa.Column('dragon_ball_series', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_data')
    # ### end Alembic commands ###
